export enum SGBD {
    AURORA_MYSQL = "aurora-mysql",
    AURORA_POSTGRES = "aurora-postgres",
    BETTER_SQLITE3 = "better-sqlite3",
    COCKROACHDB = "cockroachdb",
    CORDOVA = "cordova",
    EXPO = "expo",
    MARIADB = "mariadb",
    MONGODB = "mongodb",
    MSSQL = "mssql",
    MYSQL = "mysql",
    NATIVESCRIPT = "nativescript",
    ORACLE = "oracle",
    POSTGRES = "postgres",
    REACT_NATIVE = "react-native",
    SAP = "sap",
    SQLITE = "sqlite",
    SQLJS = "sqljs",
    SPANNER = "spanner"
}